name: Continue Integration

on:
    pull_request:
        branches:
            - '**'
    push:
        tags:
            - '**'
        branches:
            - master

jobs:
    build:
        name: PHP ${{ matrix.php-versions }}
        runs-on: ubuntu-latest
        container: shivammathur/node:latest-${{ matrix.arch }}
        strategy:
            matrix:
                arch: [ "amd64" ]
                php-versions: [ '8.1', '8.2' ]
            fail-fast: false
        steps:
            -   name: Checkout
                uses: actions/checkout@v3
            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-versions }}
                    coverage: xdebug
            -   name: Get composer cache directory
                id: composer-cache
                run: echo "::set-output name=dir::$(composer config cache-files-dir)"
            -   name: Cache composer dependencies
                uses: actions/cache@v3
                with:
                    path: ${{ steps.composer-cache.outputs.dir }}
                    # Use composer.json for key, if composer.lock is not committed.
                    # key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
                    key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                    restore-keys: ${{ runner.os }}-composer-
            -   name: Install Composer dependencies
                run: composer install --no-progress --prefer-dist --optimize-autoloader
            -   name: Run
                run: './vendor/bin/ecs --no-progress-bar'
            -   name: Run PHPStan
                run: './vendor/bin/phpstan analyse'
            -   name: Run Rector
                run: './vendor/bin/rector --dry-run '
            -   name: Run Tests
                run: './vendor/bin/phpunit --coverage-text'
